//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskLogSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleAccess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoleAccess()
        {
            this.MenuRoleAccesses = new HashSet<MenuRoleAccess>();
        }
    
        public int RoleAccessID { get; set; }
        public int RoleID { get; set; }
        public int AccessID { get; set; }
    
        public virtual Access Access { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuRoleAccess> MenuRoleAccesses { get; set; }
        public virtual Role Role { get; set; }
    }
}
